apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: {{ .Release.Namespace }}
data:
  mosquitto.conf: |
{{ .Files.Get "files/mosquitto.conf" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yml: |
{{ .Files.Get "files/prometheus.yml" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ .Release.Namespace }}
data:
  datasources.yml: |
{{ .Files.Get "files/grafana/datasources.yml" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provider
  namespace: {{ .Release.Namespace }}
data:
  dashboards.yml: |
{{ .Files.Get "files/grafana/dashboards.yml" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-json
  namespace: {{ .Release.Namespace }}
data:
  santa-maria-overview.json: |
{{ .Files.Get "files/grafana/santa-maria-overview.json" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-edge-init
  namespace: {{ .Release.Namespace }}
data:
  init.sql: |
{{ .Files.Get "files/postgres-edge-init.sql" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cloud-init
  namespace: {{ .Release.Namespace }}
data:
  init.sql: |
{{ .Files.Get "files/postgres-cloud-init.sql" | indent 4 }}
