apiVersion: v1
kind: Secret
metadata:
  name: santa-maria-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  EDGE_POSTGRES_DB: {{ .Values.postgres.edge.db | quote }}
  EDGE_POSTGRES_USER: {{ .Values.postgres.edge.user | quote }}
  EDGE_POSTGRES_PASSWORD: {{ .Values.postgres.edge.password | quote }}
  CLOUD_POSTGRES_DB: {{ .Values.postgres.cloud.db | quote }}
  CLOUD_POSTGRES_USER: {{ .Values.postgres.cloud.user | quote }}
  CLOUD_POSTGRES_PASSWORD: {{ .Values.postgres.cloud.password | quote }}
  GRAFANA_ADMIN_USER: {{ .Values.grafana.adminUser | quote }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.grafana.adminPassword | quote }}
