apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-simulator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-simulator
  template:
    metadata:
      labels:
        app: sensor-simulator
    spec:
      containers:
        - name: sensor-simulator
          image: {{ .Values.images.sensorSimulator }}
          imagePullPolicy: Never
          env:
            - name: MQTT_BROKER_HOST
              value: mosquitto
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger:4318/v1/traces
