apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: PostgreSQL Edge
    type: postgres
    uid: postgres-edge
    access: proxy
    url: postgres-edge:5432
    database: $EDGE_POSTGRES_DB
    user: $EDGE_POSTGRES_USER
    secureJsonData:
      password: $EDGE_POSTGRES_PASSWORD
    jsonData:
      sslmode: disable
      postgresVersion: 1600
