global:
  scrape_interval: 15s

scrape_configs:
  - job_name: edge-ingestion
    static_configs:
      - targets: ["edge-ingestion:8001"]

  - job_name: edge-sync
    static_configs:
      - targets: ["edge-sync:8002"]

  - job_name: cloud-api
    static_configs:
      - targets: ["cloud-api:8000"]
