postgres:
  edge:
    db: santamaria_edge
    user: santamaria
    password: changeme
  cloud:
    db: santamaria_cloud
    user: santamaria
    password: changeme

grafana:
  adminUser: admin
  adminPassword: changeme
