apiVersion: v1
kind: Secret
metadata:
  name: santa-maria-secrets
  namespace: santa-maria
type: Opaque
stringData:
  EDGE_POSTGRES_DB: santamaria_edge
  EDGE_POSTGRES_USER: santamaria
  EDGE_POSTGRES_PASSWORD: changeme
  CLOUD_POSTGRES_DB: santamaria_cloud
  CLOUD_POSTGRES_USER: santamaria
  CLOUD_POSTGRES_PASSWORD: changeme
  GRAFANA_ADMIN_USER: admin
  GRAFANA_ADMIN_PASSWORD: changeme
